# interprocedural optimization (IPO/LTO).
option(ENABLE_LINK_TIME_OPTIMIZATION "Enable link time optimization" ON)
if(ENABLE_LINK_TIME_OPTIMIZATION)
  include(CheckIPOSupported)
  check_ipo_supported(RESULT lto_supported OUTPUT lto_message)
  if(lto_supported)
    message(STATUS "${lto_message}")
    message(STATUS "Enabling link time optimization")
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_MINSIZEREL TRUE)
  else()
    message(WARNING "${lto_message}")
  endif()
endif()
